### ISSUE TITLE
Patents

### ISSUE THREAD

**Issue by renau** [lsils/mockturtle#113]
Hello,

I am evaluating to include mockturtle as part of LGraph. LGraph is a BSD3 license, but it excludes 3rd party repositories that have known patents (same was as LLVM does) (https://github.com/masc-ucsc/lgraph/blob/master/docs/CONTRIBUTING.md#Patents)

Is there any pass in mockturtle that I should not use if I am concerned about patents?

**Comment by renau** [comment]
Some correction, LGraph can include external (3rd party) code with patents, but they have to be known and not used when called from LGraph unless special IFDEF is enabled.

LGraph does not accept main contributions (not 3rd party) that has patents.

**Comment by msoeken** [comment]
For academic purposes there are no patents to worry about. But existing patent applications can affect the MIG optimization methodologies. I suggest to guard `mig_algebraic_depth_optimization` using the `IFDEF` that you mentioned.

**Comment by renau** [comment]
The goal is patents beyond academic. The grep for "mig_algebraic_depth_optimization" is empty :)
What file/methods? is it everything related to mig_*?

**Comment by msoeken** [comment]
Only [mig_algebraic_rewriting.hpp](https://github.com/lsils/mockturtle/blob/master/include/mockturtle/algorithms/mig_algebraic_rewriting.hpp).

**Comment by renau** [comment]
Thanks

**Comment by Ravenslofty** [comment]
So, I stumbled across this while researching mockturtle for Yosys. EPFL has patented [algebraic MIG manipulation](https://patents.google.com/patent/US10394988B2) as well as [MIG boolean optimisation](https://patents.google.com/patent/US20160350469A1). which means anything that uses MIG is effectively patent-infringing, and the license of mockturtle does *not* grant use of these patents.

**Comment by boschmitt** [comment]
> which means anything that uses MIG is effectively patent-infringing, and the license of mockturtle does _not_ grant use of these patents.

That does not seems to be the case. My understanding by skimming the patents is that they cover just some specific ways of optimizing MIGs---the so called, algebraic rewriting methods, and not _anything_ related to them. 

Clearly, we need to further discuss this and provide a flag to disable the patented code (or even distribute it separately).

**Comment by Ravenslofty** [comment]
> The method further comprises providing a commutativity, a majority (Ω.M), an associativity (Ω.A), a distributivity (Ω.D), an inverter propagation (Ω.I),

These are fundamental rules of MIG algebra, and putting aside that I believe these to not be patentable in the first place, it seems impossible to write a MIG transformation that does not in some way rely on the laws of MIG logic to be correct.

**Comment by boschmitt** [comment]
Your quote is from the abstract. What is claimed as invention seems to be more constrained.

> These are fundamental rules of MIG algebra, and putting aside that I believe these to not be patentable in the first place, it seems impossible to write a MIG transformation that does not in some way rely on the laws of MIG logic to be correct.

I'm by no means an expert on patents, but I am quite sure the fundamentals rules of MIG algebra are not be patentable. Furthermore, algebraic manipulation of Majority logic is known since the 60s [[1]](https://ieeexplore.ieee.org/abstract/document/5219289). Indeed, I think this paper has a table containing all the identities used on the patent.

**Comment by hriener** [comment]
The MIG optimization methodology developed in Luca Amaru's thesis has been patented. The Boolean methods developed in `mockturtle` follow different ideas and have a different codebase. These methods are called ``Boolean'' (not algebraic) because they are typically based on truth table manipulations and the rules of Boolean logic (and not algebraic rewriting rules as defined in the thesis/patent).

**Comment by hriener** [comment]
If there are no new arguments in this discussion, then I would close the issue again.
