### ISSUE TITLE
Optimization algorithms to support names_view<sequential<xxx_network>>

### ISSUE THREAD

**Issue by phyzhenli** [lsils/mockturtle#588]
**Describe the bug**
Hi~ I checked the test folder and found that the optimization commands (e.g. balancing, cut_rewrite, and etc.) are not tested for names_view<sequential<xxx_network>> except for the `cleanup` command, is it because these commands do not currently support optimization for names_view<sequential<xxx_network>>? Thanks!

**To Reproduce**
1. Which version of `mockturtle` (commit or PR number) are you using? (Preferably the latest, unless there are special reasons.)
Commits on Dec 22, 2022
2. A complete snippet of your code (usually a cpp file including `main`).
N/A
3. The benchmark circuit for which the error occurs. Please try to minimize it first by using the testcase minimizer ([docs](https://mockturtle.readthedocs.io/en/latest/debugging.html#testcase-minimizer), [example code](https://github.com/lsils/mockturtle/blob/master/examples/minimize.cpp)).
N/A
4. Error messages or print-outs you see (if any) (preferably copy-pasted as-is).
N/A

**Environment**
 - OS: [e.g. Linux]  N/A
 - Compiler: [e.g. GCC 12]  N/A
 - Compilation mode: [DEBUG or RELEASE]  N/A

**Additional context**
N/A

**Check list**
 * [ ] I have tried to run in DEBUG mode and there was no assertion failure (or the reported bug is an assertion failure).
 * [ ] I have made sure that the provided code compiles and the testcase reproduces the error.
 * [ ] I have minimized the testcase.

**Comment by lee30sonia** [comment]
This is because `sequential` was developed after the implementations of those algorithms. In fact, support of sequential networks in mockturtle is currently fairly limited, as our developers do not have actual use case in that matter. 
Thus, the specific combinations of interfaces, views, and algorithms are not tested because they are not of interest or in a top priority to us, but it doesn't mean that they will not work. As many mockturtle algorithms are designed to be generic, it is possible that the aforementioned combinations work smoothly without problems. We welcome, of course, external contributions of special-case fixes or tests if they make sense.
