### ISSUE TITLE
The `blif_reader` to mig directly is not worked as expected

### ISSUE THREAD

**Issue by wjrforcyber** [lsils/mockturtle#620]
**Describe the bug**
The `blif_reader` to mig directly is not worked as expected with 
`error: static assertion failed: Ntk does not implement the create_node function or the create_cover_node function`

**To Reproduce**
version: 
latest version

Reproduce with:
```
mockturtle::mig_network ntk;
mockturtle::names_view<mockturtle::mig_network> names_view{ntk};
lorina::return_code result = lorina::read_blif(filename, mockturtle::blif_reader(names_view));
```

Error
```
error: static assertion failed: Ntk does not implement the create_node function or the create_cover_node function
static_assert( has_create_node_v<Ntk> || has_create_cover_node_v<Ntk>, "Ntk does not implement the create_node function or the create_c
over_node function" );
```

**Environment**
 Centos 8
 Debug mode

**Check list**
 * [x] I have tried to run in DEBUG mode and there was no assertion failure (or the reported bug is an assertion failure).
 * [x] I have made sure that the provided code compiles and the testcase reproduces the error.
 * [x] I have minimized the testcase.

**Comment by lee30sonia** [comment]
This is the expected behavior. The BLIF format specifies blocks of logic functions, i.e., a k-LUT network in our terminology. We cannot ensure that the input file only contains MAJ-3 gates, thus reading a BLIF file as an MIG is not supported.
What you could do is reading BLIF as a klut_network, and then use one of the [mapping](https://mockturtle.readthedocs.io/en/latest/algorithms/mapper.html) or [graph conversion](https://mockturtle.readthedocs.io/en/latest/algorithms/klut_to_graph.html) methods to convert into mig_network.

**Comment by wjrforcyber** [comment]
> This is the expected behavior. The BLIF format specifies blocks of logic functions, i.e., a k-LUT network in our terminology. We cannot ensure that the input file only contains MAJ-3 gates, thus reading a BLIF file as an MIG is not supported.
> What you could do is reading BLIF as a klut_network, and then use one of the [mapping](https://mockturtle.readthedocs.io/en/latest/algorithms/mapper.html) or [graph conversion](https://mockturtle.readthedocs.io/en/latest/algorithms/klut_to_graph.html) methods to convert into mig_network.

I thought since aig reader is supported, an automatic convert from aig to mig is supported either. Thanks for your reply.

**Comment by lee30sonia** [comment]
I'm not sure what you mean by "aig reader is supported", but if you have an AIGER file, you could read_aiger with mig_network, that should work.
